name: Process dataset on S3 upload

on:
  repository_dispatch:
    types: [s3_upload]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - run: pip install -r requirements.txt

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run dataset processing script
        run: |
          python scripts/rowharv_imgavg.py \
            "${{ github.event.client_payload.bucket }}" \
            "${{ github.event.client_payload.key }}"
